### PR TITLE
Feature: Option to skip checking main module

### PR DESCRIPTION
**Pull request by mjemmeson**
Hi,

Firstly, thanks for your module. This PR is for a small change to make it more compatible with Dist::Zilla::Plugin::VersionFromMainModule - currently there will always be the warning about "No #VERSION in module...".

I considered changing the regex to not add the version if there was one already, but thought that was more fragile and could hide any problems (for example if an incorrect version number was copy-and-pasted in).

thanks,
Michael

### CODE REVIEW

**Comment by plicease** [comment]
Looks good, although I'd like to know why it is failing the link check in CI.  It's complaining about `Dist::Zilla::Plugin::VersionFromMainModule` but that is a legit module as far as I can tell!

**Comment by plicease** [comment]
diagnostic https://travis-ci.org/plicease/Dist-Zilla-Plugin-OurPkgVersion/jobs/481374488#L2065

**Comment by plicease** [comment]
I made some tweaks to get pass the perl critic tests.  In particular I ended up bumping the requirement of `Dist::Zilla` to 5.038, instead of using a different finder.  I'm not even all that keen on supporting dzil prior to 6 tbh.

**Comment by plicease** [comment]
This is included in the 0.14 release now on its way to CPAN.  Thanks for the contribution.

**Comment by mjemmeson** [comment]
Thanks, and sorry for not replying earlier - I started looking into the POD link checking failure, but couldn't reproduce locally and then forgot about it!

**Pull request merged**
